package us.zingalicio.handlefish;

public class Keys 
{
	public static final String PERMISSION_BAN = "handlefish.ban";
	public static final String PERMISSION_UNBAN = "handlefish.unban";
	public static final String PERMISSION_CHECK_BIOME = "handlefish.biome.check";
	public static final String PERMISSION_GIVE = "handlefish.give";
	public static final String PERMISSION_GIVE_INFINITE = "handlefish.give.infinite";
	public static final String PERMISSION_GIVE_OTHERS =	"handlefish.others.give";
	public static final String PERMISSION_GIVE_OTHERS_INFINITE = "handlefish.others.give.infinite";
	public static final String PERMISSION_HEAD =	"handlefish.head";
	public static final String PERMISSION_HEAD_OTHERS =	"handlefish.others.head";
	public static final String PERMISSION_RELOAD = "handlefish.reload";
	public static final String PERMISSION_HOME = "handlefish.home";
	public static final String PERMISSION_HOME_OTHERS = "handlefish.others.home";
	public static final String PERMISSION_SET_HOME = "handlefish.home.set";
	public static final String PERMISSION_SET_HOME_OTHERS = "handlefish.others.home.set";
	public static final String PERMISSION_KIT = "handlefish.kit"; //Append with ".kitname"
	public static final String PERMISSION_KIT_LIST = "handlefish.kit.list"; //Append with ".kitname"
	public static final String PERMISSION_KIT_OTHERS = "handlefish.others.kit"; //Append with ".kitname"
	public static final String PERMISSION_EDIT_KITS = "handlefish.kits";
	public static final String PERMISSION_SPAWN_MOB = "handlefish.spawnmob";
	public static final String PERMISSION_BUTCHER = "handlefish.butcher";
	public static final String PERMISSION_MORE = "handlefish.more";
	public static final String PERMISSION_FLIGHT = "handlefish.movement.fly";
	public static final String PERMISSION_FLIGHT_OTHERS = "handlefish.others.movement.fly";
	public static final String PERMISSION_FLIGHT_SPEED = "handlefish.movement.flyspeed";
	public static final String PERMISSION_FLIGHT_SPEED_OTHERS = "handlefish.others.movement.flyspeed";
	public static final String PERMISSION_WALK_SPEED = "handlefish.movement.walkspeed";
	public static final String PERMISSION_WALK_SPEED_OTHERS = "handlefish.others.movement.walkspeed";
	public static final String PERMISSION_BUILD_MODE = "handlefish.movement.buildmode";
	public static final String PERMISSION_BUILD_MODE_OTHERS = "handlefish.others.movement.buildmode";
	public static final String PERMISSION_BAN_OVERRIDE = "handlefish.ban.override";
	public static final String PERMISSION_SELF = "handlefish.self";
	public static final String PERMISSION_GOD = "handlefish.god";
	public static final String PERMISSION_GOD_OTHERS = "handlefish.others.god";
	public static final String PERMISSION_HEAL = "handlefish.heal";
	public static final String PERMISSION_HEAL_OTHERS = "handlefish.others.heal";
	public static final String PERMISSION_CLEAR = "handlefish.clear";
	public static final String PERMISSION_CLEAR_OTHERS = "handlefish.others.clear";
	public static final String PERMISSION_KICK = "handlefish.kick";
	public static final String PERMISSION_PUNISH = "handlefish.punish";
	public static final String PERMISSION_PUNISH_OTHERS = "handlefish.others.punish";
	public static final String PERMISSION_SPAWN = "handlefish.spawn";
	public static final String PERMISSION_SPAWN_OTHERS = "handlefish.others.spawn";
	public static final String PERMISSION_SET_SPAWN = "handlefish.spawn.set";
	public static final String PERMISSION_REQUEST_TELEPORT = "handlefish.tpa";
	public static final String PERMISSION_TELEPORT = "handlefish.tp";
	public static final String PERMISSION_TELEPORT_OTHERS = "handlefish.others.tp";
	public static final String PERMISSION_TELEPORT_PRIVACY = "handlefish.tp.privacy";
	public static final String PERMISSION_TELEPORT_OVERRIDE = "handlefish.tp.override";
	public static final String PERMISSION_CHECK_TIME = "handlefish.time.check";
	public static final String PERMISSION_SET_TIME = "handlefish.time.set";
	public static final String PERMISSION_CHECK_PTIME = "handlefish.ptime.check";
	public static final String PERMISSION_CHECK_PTIME_OTHERS = "handlefish.others.ptime.check";
	public static final String PERMISSION_SET_PTIME = "handlefish.ptime.set";
	public static final String PERMISSION_SET_PTIME_OTHERS = "handlefish.others.ptime.set";
	public static final String PERMISSION_WARP = "handlefish.warp"; //Append with ".warpname"
	public static final String PERMISSION_WARP_OTHERS = "handlefish.others.warp"; //Append with ".warpname"
	public static final String PERMISSION_LIST_WARP = "handlefish.warp.list"; //Append with ".warpname"
	public static final String PERMISSION_EDIT_WARPS = "handlefish.warps";
	public static final String PERMISSION_WEATHER = "handlefish.weather.check";
	public static final String PERMISSION_SET_WEATHER = "handlefish.weather.set";
	
	public static final String OPTION_BUILD_MODE = "handlefish.movement.buildmode";
	public static final String OPTION_BUILD_MODE_REACH = "handlefish.movement.reach";
	public static final String OPTION_BUILD_MODE_DELAY = "handlefish.movement.delay";
	public static final String OPTION_FLIGHT = "handlefish.movement.flight";
	public static final String OPTION_FLIGHT_SPEED = "handlefish.movement.flyspeed";
	public static final String OPTION_WALK_SPEED = "handlefish.movement.walkspeed";
	public static final String OPTION_TIME = "handlefish.24hr";
	public static final String OPTION_GOD = "handlefish.godmode";
	public static final String OPTION_BAN_OVERRIDE = "handlefish.unbannable";
	public static final String OPTION_DISPLAY_NAME = "displayname";
	public static final String OPTION_JOIN_MESSAGE = "joinmessage";
}
